---
title: "GHVE Classifiers"
output: html_notebook
---



```{r}
GHVimp<-df5[, c('GHV','MENV','HEV','CEDV','Duck','Pig',
                'HH.46.to.60','Cat','BDBV','WildContact','Dog',
                'Cattle',
                'Parts.Disposed')]
```

```{r}
summary(GHVimp)
```

```{r}
library(caret)
```

```{r}
#Create train/test split 70/30
set.seed(1234)
train <- sample(nrow(GHVimp), 0.7*nrow(GHVimp), replace = FALSE)
TrainSet <- GHVimp[train,]
ValidSet <- GHVimp[-train,]
summary(TrainSet)
summary(ValidSet)
TrainingParameters <- trainControl(method = "repeatedcv", number = 10, repeats=10)
```

```{r}
library(DMwR)

## Smote : Synthetic Minority Oversampling Technique To Handle Class Imbalance In Binary Classification; code below puts it at 1:1 balance
balanced.data <- SMOTE(GHV ~., TrainSet, perc.over = 100)

as.data.frame(table(balanced.data$GHV))
```

```{r}
set.seed(1234)
library(klaR)
NaiveModel <- train(TrainSet[,-17], TrainSet$GHV, 
                    method = "nb",
                    preProcess=c("scale","center"),
                    trControl= TrainingParameters,
                    na.action = na.omit
)

#Predictions
NaivePredictions <-predict(NaiveModel, ValidSet, na.action = na.pass)
cmNaive <-confusionMatrix(NaivePredictions, ValidSet$GHV)
```

```{r}
NaivePredictions <-predict(NaiveModel, ValidSet, na.action = na.pass)
```

```{r}
cmNaive <-confusionMatrix(NaivePredictions, ValidSet$GHV)
```

```{r}
cmNaive
```

```{r}
library(pROC)
#Calculate ROC curve
rocCurve.nb<- roc(ValidSet$GHV,as.numeric(NaivePredictions))
```

```{r}
plot(rocCurve.nb,col=c(1))
```

```{r}
auc(rocCurve.nb)
```

```{r}
set.seed(1234)
NNModel <- train(TrainSet[,-17], TrainSet$GHV,
                  method = "nnet",
                  trControl= TrainingParameters,
                  preProcess=c("scale","center"),
                  na.action = na.omit)
```

```{r}
NNPredictions <-predict(NNModel, ValidSet)
# Create confusion matrix
cmNN <-confusionMatrix(NNPredictions, ValidSet$GHV)
```

```{r}
cmNN
```

```{r}
library(pROC)
#Calculate ROC curve
rocCurve.nn<- roc(ValidSet$GHV,as.numeric(NNPredictions))
```

```{r}
#plot the ROC curve
plot(rocCurve.nn,col=c(1))
```

```{r}
auc(rocCurve.nn)
```

```{r}
set.seed(1234)
library(caret)
library(C50)
```

```{r}
# Train a model with above parameters. We will use C5.0 algorithm
DecTreeModel <- train(GHV ~ ., data = TrainSet, 
                      method = "C5.0",
                      preProcess=c("scale","center"),
                      trControl= TrainingParameters,
                      na.action = na.omit)
```

```{r}
#Predictions
DTPredictions <-predict(DecTreeModel, ValidSet, na.action = na.pass)
# Print confusion matrix and results
cmTree <-confusionMatrix(DTPredictions, ValidSet$GHV)
```

```{r}
cmTree
```

```{r}
library(pROC)
#Calculate ROC curve
rocCurve.dt<- roc(ValidSet$GHV,as.numeric(DTPredictions))
```

```{r}
#plot the ROC curve
plot(rocCurve.dt,col=c(1))
```

```{r}
auc(rocCurve.dt)
```

